### ISSUE TITLE
getAttachments-Funktion benötigt

### ISSUE THREAD

**Issue by JanMalch** [FW97/Forum-INF16B#190]
Es wird noch eine Funktion benötigt, um die Attachments eines  Postings zu holen.
Entweder am DAO- oder Posting-Objekt. Habe pseudo in posting.jsp `dao.getAttachmentsByPostingId(postingId)` benutzt.

**Comment by AndMSWDE97** [comment]
Pull request mit der Funktion ist erstellt worden. Die Funktion wurde noch nicht getestet, sollte allerdings funktionieren.

**Comment by AndMSWDE97** [comment]
Funktion wurde getestet und funktioniert. Issue kann geschlossen werden
