### ISSUE TITLE
Zur Verlinkung sollten a tags benutzt werden, und nicht div tags

### ISSUE THREAD

**Issue by carstenhag** [FW97/Forum-INF16B#44]
Gefunden in https://github.com/FW97/Forum-INF16B/blob/master/forum/forum/postings.jsp#L27:

```html
<div class=post onClick="window.location='posting.jsp?postid=<%=postID%>'">
```
Sollte entweder `<div class="post"><a>//content</a></div>` oder  
`<a><div class="post">//content</div></a>` sein, unterscheidet sich an was klickbar sein wird, ob nur die textzeilen oder das ganze div.

**Comment by mortenterhart** [comment]
Das wird noch erledigt, momentan kümmern wir uns um die Verarbeitung der Parameter und das Laden der Posts aus der Datenbank, dabei ändern wir das HTML sowieso noch

**Comment by mortenterhart** [comment]
Neue Version hochgeladen und das a-Tag wurde eingefügt (siehe #52)

**Comment by carstenhag** [comment]
Danke :)
